Dav1dde/glad

glad/lang/c/generator.py
glad/lang/c/loader/gl.py
glad/lang/c/loader/glx.py
glad/lang/c/loader/wgl.py

Invoke `glGetString(GL_EXTENSIONS)` only once (instead of
GL_NUM_EXTENSIONS), and `glGetStringi(GL_EXTENSIONS)` only
GL_NUM_EXTENSIONS (instead of roughly
GL_NUM_EXTENSIONS*GL_NUM_EXTENSIONS).
This is particularly handy when obtaining traces of applications that
use GLAD, which otherwise get over 10K of redundant calls nowadays
(and probably much more in the future).

Get OpenGL extensions strings only once.

---

CMakeLists.txt

The path to the glad header is incorrect, causing the custom command to regenerate the source files on every build. This simply fixes the path, so that the command only generates the sources when they are missing.

cmake: fix typo in GLAD_SOURCES

---

CMakeLists.txt

This change allows source generation options to be configurable through CMake. For example, if an OpenGL 3.2 core profile was desired:
```
set(GLAD_PROFILE "core" CACHE INTERNAL "OpenGL profile")
set(GLAD_API "gl=3.2" CACHE INTERNAL "API type/version pairs, like \"gl=3.2,gles=\", no version means latest")
add_subdirectory("${PROJECT_SOURCE_DIR}/dependencies/glad")
```

cmake: add support for options

---

glad/lang/c/loader/gl.py

When C DLL version is used, GLVersion variable cannot be accessed because of omitting export. I changed "extern" to "GLAPI" and moved the statement to the next of API generation.

c: Fix a directive of GLVersion for access in DLL.

---

README.md
glad/__main__.py
glad/lang/c/generator.py
glad/lang/c/loader/__init__.py
glad/lang/c/loader/glx.py
glad/lang/c/loader/wgl.py
glad/lang/common/loader.py

Basicly I have made 3 changes to improve the usage of the C generator especially on Windows:
- `--local-files`: This command line option informs Glad to put all files into a single directory. Inside the MSVC environment it is uncommon to split files into seperate directories for headers and sources. Additionally it is no longer necessary to add the Glad header directory to the include paths which is much more convenient.
- `--omit-khrplatform`: This option prevents the often unnecessary file `khrplatform.h` from getting downloaded and included.
- I changed `LoadLibraryA` to `LoadLibraryW` since the usage of the old Ansi functions is generally not recommended anymore.
It would propably make sense to add some of these options to other generators but this is outside the scope of this pull …

Improve the C generator to especially better support for the Windows platform

---

CMakeLists.txt

In CMakeLists.txt, this seems unnecessary:
`set(Python_ADDITIONAL_VERSIONS 2)`
Using pyenv where both python 2 and python 3 are present, but where python 3 is the default python in use, this line seems to make cmake favour python 2, resulting in failure to find python.

cmake: allow cmake to use primary python

---

glad/lang/d/generator.py
glad/lang/d/loader/__init__.py

Old import was still there in two places, the deprecation messages were bothering me a bit so I decided to make a PR. It's used in other places in the code already too, so it *should* be fine.

d: change deprecated imports to non-deprecated ones for windows api

---

glad/lang/nim/loader/gl.py

I got following compile error with Nim 0.20.0.
```
glad/gl.nim(2259, 14) Error: 'nil' is now invalid for 'string'; compile with --nilseqs:on for a migration period; usage of '==' is a user-defined error
```
Empty ``string`` should be checked with ``someString.len == 0`` in current Nim.

nim: fix compile error when using latest nim

---

glad/generator/c/templates/egl.c

EGL loading was failing for a display of EGL_NO_DISPLAY.
Allow loading EGL 1.5 and above since eglQueryString supports
EGL_NO_DISPLAY in this case.

glad: Fix EGL loading for EGL_NO_DISPLAY on EGL 1.5 and above

---

CMakeLists.txt
glad/__main__.py
glad/lang/c/generator.py
glad/lang/common/generator.py

This PR enhances the ability to generate GLAD (1) from CMake, but also addresses other generator issues. 
First of all, it fixes a bug that produces invalid builds when a different `GLAD_SPEC` than `gl` was specified (see issue #314). Since all other specs depend on the `gl` spec (i.e. the generated `glad.h` and `glad.c` code) to be present, I also had to introduce support for generating code for multiple specs, similar to PR #276. However, different to it, this PR does not introduce an additional command line argument, but instead extents `GLAD_SPEC` and `--spec` to support a list of specs instead. Furthermore, this PR also adds the generated headers to the install list, allowing to properly install the CMake target.
Since the `gl` spec is always required, it is added by default (if not …

Enhanced CMake support.

---

cmake/CMakeLists.txt
cmake/WriteFile.cmake

Changes:
- Switched over `add_custom_command()` to create a file-based dependency with `OUTPUT ${GLAD_FILES} ${GLAD_ARGS_PATH}` on which added libraries depend on.
This `${TARGET}-generate` step is properly re-triggered only if one of its arguments changes and regeneration is needed.
Kept the `remove_directory()` for safety, but It may not be needed given how `GLAD_FILES` are very selective.
Sources should not be deleted afterwards, no reason to hide what we just generated, that's harder to debug.
- Fixed Shared Library building
- Not outrageous CMake minimal version bump to 3.2
- Allowed Interface Libraries for those with CMake 3.19+
- Removed unused `LIBTYPE`
Related to #319

Glad2 CMake Rework

---

glad/generator/c/templates/gl.c

If an unsupported GL_VERSION prefix string is encountered, the sscanf()
call used to parse the version number values may fail. When this occurs,
"major" and "minor" will be left uninitialized, which leads to undefined
behavior when using these values later.
This change addresses the issue by making sure "major" and "minor" are
initialized to zero. If the sscanf() call fails, subsequent checks
against these version number values will at least have consistent
results.

c: zero-initializes parsed GL version numbers

---

glad/generator/c/templates/gl.c
glad/generator/d/templates/loader/gl.d
glad/generator/volt/templates/loader/gl.volt

OpenGL SC drivers return GL_VERSION strings with the format "OpenGL SC
N.M vendor-specific information", so the string "OpenGL SC " should be
included in the list of prefixes checked when parsing the GL_VERSION
string.

glad: adds OpenGL SC support for GL_VERSION string parsing

---

glad/files/eglplatform.h

eglplatform.h was missing for reproducible builds that include egl. Can be verified by:
`cmake -G Ninja -DGLAD_REPRODUCIBLE=ON -DGLAD_SPEC="egl" -DGLAD_API="gl=,gles2=" -DGLAD_ALL_EXTENSIONS=ON`

glad: add eglplatform.h for reproducible builds that includes egl

---

glad/generator/c/templates/base_template.c
glad/generator/c/templates/base_template.h
glad/generator/c/templates/gl.c
glad/generator/c/templates/vk.c

Instead of a separate struct that needs to be copied by-value. This will reduce the risk of accidentally ending up with an inconsistent context state.
We still need a default context in the even that a user loads an `mx-global` context without ever supplying a custom struct, but this is easy enough to return in an ad-hoc fashion whenever `gladGet*Context` is called without a context otherwise being bound.
(Incidentally, the way this logic is implemented also lets you recover the global context by explicitly calling `gladSet*Context(NULL)`)

c: store mx-global context as a pointer

---

glad/parse.py

Having a way to filter Types by their parents allows Vulkan generators to load functions by type (similar to volk), and Member's enums can be used to set the array size of a particular Member.
This change is used with the generator mentioned in issue #368

Implement is_descedant for Type and parse Type's parent and Member's enum

---

cmake/CMakeLists.txt

When building cmake-projects using ninja as generator and if multiple APIs are specified, khrplatform.h is added multiple times to the list of files to compile. This triggers an error in ninja: "duplicate build rules".
Simply removing duplicate files from the GGC_FILES list fixes this issue.

Ninja: Fixed "duplicate build rules" error

---

glad/lang/c/loader/wgl.py

This is named gladUnloadWGL in the header file, and the corresponding load-function also has a WGL suffix. So it seems safe to assume that the GLX suffix is a typo.

c: correct name of unload-function

---

cmake/CMakeLists.txt

FindPythonInterp is deprecated. The new module finds new way to locate the python environment. In some cases the deprecated FindPythonInterp found the incorrect python interpreter.

Use FindPython instead of FindPythonInterp

---

glad/generator/c/templates/gl.c

This fixes issue #446 by being more flexible when parsing extensions.
If the array version is available, it is used, else, it falls back on space separated string.
In addition, if the implementation doesn't have any extension, parsing doesn't fail anymore and if malloc fails, extensions parsing fails.

Fix extensions loading and parsing

---

glad/generator/c/templates/loader/gles2.c

Check for a defined variable instead of a 1/0 flag, for symmetry with GLAD_GL, GLAD_GLES2 and other user-facing defines.
Fixes: https://github.com/Dav1dde/glad/issues/460

c: don't warn on undefined GLAD_GLES2_USE_SYSTEM_EGL

---

.gitignore
example/c/gl_glfw.c

Patch for issue #463 which can cause portability issues in the future by defining `GLAD_GL_IMPLEMENTATION` before glad import in GLFW example.
This patch does not stress nor attempt to fix any issues with the library itself, but edits the example in question so consumers don’t make the mistake of not defining the required macro.
> An alternative solution might be to include GLFW before glad, but I haven’t had the chance to confirm. Don’t take my word for it.
Also added .vscode to .gitignore. If this is
an issue please let me know so I can remove
it before the pull.
Thank you @Dav1dde for helping me troubleshoot the version checking issue.

Defined GLAD_GL_IMPLEMENTATION to GLFW example

---

.github/workflows/glad2.yaml

Fix the following warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

ci: bump actions versions

---

glad/lang/c/loader/gl.py

Make types consistent as it troubles the GCC analyzer.
This will fix issue #466 (tested on a stripped version of generated file on Godbolt).

Fix issue #466
